=== AdrianVideiraRial/Boletin02/hoteles.dtd
<!ELEMENT Ficha (Hotel)>
<!ELEMENT Hotel (telefono,direccion,numero,ciudad,pais,estrellas,descripcion,habitaciones)>
<!ATTLIST Hotel nombre CDATA #REQUIRED>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT estrellas (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT habitaciones (simples,dobles,triples,suites)>
<!ELEMENT simples (#PCDATA)>
<!ELEMENT dobles (#PCDATA)>
<!ELEMENT triples (#PCDATA)>
<!ELEMENT suites (#PCDATA)>

=== AdrianVideiraRial/Boletin02/hoteles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Ficha SYSTEM "hoteles.dtd">
<Ficha>
    <Hotel nombre="Hotel Hilton">
        <telefono>665541221</telefono>
        <direccion>Avenida Gran Via</direccion><numero> 45 </numero>
        <ciudad>Madrid</ciudad>
        <pais>España</pais>
        <estrellas>5</estrellas>
        <descripcion>Hotel situado en el centro de la ciudad con camas confortables y amplias</descripcion>
        <habitaciones>
            <simples>20</simples>
            <dobles>45</dobles>
            <triples>10</triples>
            <suites>10</suites>
        </habitaciones>
    </Hotel>
</Ficha>

<!-- Completar este documento para registrar hoteles,
    donde tengas nombre, teléfono, dirección(calle y número),
    ciudad, país, numero de estrellas, descripción del hotel,
    número habitaciones individuales, habitaciones dobles,
    habitaciones triples, suites.
    Probar si es un documento bien formado.
-->
